config/routes.rb
NewsSystem::Application.routes.draw do
  devise_for :users

  resources :articles do
    post :like, on: :member
    post :dislike, on: :member
  end

  resources :user do
    resources :articles
  end

  root to: 'articles#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    can :read, Article
    can :create, Article if user.persisted?
    can :manage, Article, user_id: user.id
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, :content, presence: true

  paginates_per 10

  scope :by_popularity, -> { order('articles.votes DESC') }
  scope :by_newest, -> { order('articles.created_at DESC') }
  scope :proper_order, -> { order('articles.votes DESC, articles.created_at DESC') }
  scope :by_user_id, -> (id) { where("user_id = ?", id) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show, :like, :dislike]
  before_filter :new_article, only: [:create]
  before_filter :find_articles, only: [:index, :like, :dislike]
  load_resource except: [:create, :index]
  before_filter :remember_voting, only: [:like, :dislike]
  authorize_resource except: [:index, :like, :dislike]

  helper_method :already_voted?

  def index
  end

  def new
  end

  def create
    if @article.save
      flash[:notice] = 'The news has been added'
      redirect_to article_path(@article)
    else
      render action: 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update_attributes(safe_params)
      flash[:notice] = 'The article has been updated'
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'The article has been deleted'
    redirect_to user_articles_path(current_user)
  end

  def like
    @article.increment(:votes)
    respond_to do |format|
      @article.save
      format.html { redirect_to root_path }
      format.js {}
    end
  end

  def dislike
    @article.decrement(:votes)
    respond_to do |format|
      @article.save
      format.html { redirect_to root_path }
      format.js {}
    end
  end

  private

  def safe_params
    params[:article].permit(:title, :content)
  end

  def new_article
    @article = current_user.articles.build(safe_params)
  end

  def find_articles
    @articles = Article.proper_order.page(params[:page])
    @articles = @articles.by_user_id(params[:user_id]) if params[:user_id]
  end

  def remember_voting
    session[@article.id] = true
  end

  def already_voted?(article)
    session[article.id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/articles/_articles.html.haml
- @articles.each do |article|
  %li{ id: "article_#{article.id}"}
    %h3= link_to article.title, article_path(article)
    %p= "Votes: #{article.votes}"
    %p= "Created: #{time_ago_in_words(article.created_at) }"
    - unless already_voted?(article)
      .voting
        %span= link_to 'Like', like_article_path(article,
        page: params[:page] || 1, user_id: params[:user_id]), method: :post, remote: true
        %span=link_to 'Disike', dislike_article_path(article,
        page: params[:page] || 1, user_id: params[:user_id]), method: :post, remote: true

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    %ul
      - @article.errors.full_messages.each do |m|
        %li= m

  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :content
    = f.text_area :content

  = f.submit

app/views/articles/dislike.js.erb
$("ul#articles").empty();
$('<%= escape_javascript(render(:partial => "articles"))%>').appendTo('#articles');

app/views/articles/edit.html.haml
= render 'form'

app/views/articles/index.html.haml
%ul#articles{ style: 'list-style: none;'}
  = render 'articles'
= paginate @articles

app/views/articles/like.js.erb
$("ul#articles").empty();
$('<%= escape_javascript(render(:partial => "articles"))%>').appendTo('#articles');

app/views/articles/new.html.haml
= render 'form'

app/views/articles/show.html.haml
%h3= @article.title
%p= @article.content
%p= "User: #{@article.user.email}"
%p= "Created at: #{ time_ago_in_words(@article.created_at) } ago"
- if can? :manage, @article
  %p= link_to 'Edit', edit_article_path(@article)
  %p= link_to 'Delete', article_path(@article), method: :delete

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "NewsSystem"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to 'News System', root_path, class: 'brand'
          .container.nav-collapse
            %ul.nav
              - if user_signed_in?
                %li= link_to "Add news", new_article_path
                %li= link_to "My news", user_articles_path(current_user)
                %li= link_to "Sign out", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "Sign in", new_user_session_path
                %li= link_to "Sign up", new_user_registration_path

    .container-fluid

      .row-fluid
        .span2
        .span8
          = bootstrap_flash
          = yield
        .span2

      %footer.navbar-bottom
        .span3.offset6
          %p &copy; Company 2014